### PR TITLE
Fix watch mode and support watching single file

### LINKED ISSUE #185: Watch mode does not work
Watch mode, `-w` gives an error. 
```
clean src -w
```

Watch mode does not support watching a single file
```
clean src/factorial.cl -w
```

### PR DESCRIPTION
**Pull request by sumanthyedoti**
fixes #185

### CODE REVIEW

File: lib/cli.js [hunk 1]
```diff
@@ -172,16 +172,21 @@ const removeFile = (outfile, changedInpfile) => {
...
+  const isWatchMode = argsObj.w
+  if (!inputArg && !isWatchMode) {
     if (argsObj.v) showAndExit(version)
     showAndExit(help)
   }
-  if (inputArg && !isWatchFolder) {
+  if (!isDirectory(inputArg)) {
+    const fileExt = path.parse(inputArg).ext
+    if (fileExt !== '.cl') {
+      showAndExit(`${inputArg} is not a clean file`, 'error')
```
Comment (angadgill92) [inline lib/cli.js]:
```suggestion
      showAndExit(`${inputArg} is not a Clean file`, 'error')
```

**Review by angadgill92 — CHANGES_REQUESTED** [review]
